name: C/C++ CI Linux

on: [push, pull_request]

jobs:

  build:
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04, ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    - name: install dependencies on [${{ matrix.os }}]
      run: |
        sudo apt update
        sudo apt install -y build-essential libcpputest-dev lcov libncurses-dev cppcheck
    - name: autoreconf
      run: autoreconf -ivf
    - name: configure
      run: ./configure
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
