name: C/C++ CI Linux

on: [push, pull_request]

jobs:

  build:
    runs-on: ubuntu-${{ matrix.version }}-${{ matrix.architecture }}
    strategy:
      matrix:
        version:
          - 20.04
          - 22.04
          - latest
        architecture:
          - amd64
          - arm64

    steps:
    - uses: actions/checkout@v4
    - name: install dependencies on [${{ matrix.os }}-${{ matrix.architecture }}]
      run: |
        sudo apt update
        sudo apt install -y build-essential libcpputest-dev lcov libncurses-dev cppcheck
    - name: autoreconf
      run: autoreconf -ivf
    - name: configure
      run: ./configure
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
