name: C/C++ CI Windows with MinSYS2

on: [push, pull_request]

jobs:

  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}

    steps:
      - name: config msys2
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: git
          pacboy: >-
            autotools:p
            gcc:p
            make:p
            lcov:p
            ncurses
            cpputest:p
            cppcheck:p
      - name: config git
        run: git config --global core.autocrlf input
      - name: checkout source code
        uses: actions/checkout@v4
      - name: autoreconf
        run: autoreconf -ivf
      - name: configure
        run: ./configure
      - name: configure
        run: ./configure
      - name: make
        run: make
      - name: make check
        run: make check
      - name: make distcheck
        run: make distcheck
