name: C/C++ CI Windows with CYGWIN

on: [push, pull_request]

jobs:

  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: bash --noprofile --norc -eo pipefail -o igncr {0}

    steps:
      - name: config git
        run: git config --global core.autocrlf input
      - name: checkout source code
        uses: actions/checkout@v4
      - name: config cywin
        uses: egor-tensin/setup-cygwin@v4
        with:
          install-dir: C:\cygwin
          env: winsymlinks:native
          packages: >-
            curl
            autoconf
            automake
            gcc-g++
            make
            cppcheck
            libncurses-devel
      - name: autoreconf
        run: autoreconf -ivf
      - name: configure
        run: ./configure
      - name: configure
        run: ./configure
      - name: make
        run: make
      - name: make check
        run: make check
      - name: make distcheck
        run: make distcheck
